### ISSUE TITLE
// Set just the background console.log(chalk(null, "gray")("this will be the default text color on gray"));

### ISSUE THREAD

**Issue by matthewoates** [ccheever/chalk256#2]
from your README:

// Set just the background
console.log(chalk(null, "gray")("this will be the default text color on gray"));

That code blows up.
Error: Don't understand the color 'null'
    at getColorNumber (/Users/matt/workspace/junk/node_modules/chalk256/node_modules/crayon/crayon.js:241:13)
    at ansiStyle (/Users/matt/workspace/junk/node_modules/chalk256/node_modules/crayon/crayon.js:258:29)
    at t (/Users/matt/workspace/junk/node_modules/chalk256/node_modules/crayon/crayon.js:292:16)
    at general (/Users/matt/workspace/junk/node_modules/chalk256/node_modules/crayon/crayon.js:299:21)
    at module.exports.crayon (/Users/matt/workspace/junk/node_modules/chalk256/node_modules/crayon/crayon.js:307:34)
    at repl:1:14
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)

chalk256 v4.0.0 installed via NPM.
node v0.10.26

**Comment by ccheever** [comment]
Hi, sorry. I changed the docs and everything with this commit and republished the package.
I think the new interface is better.
Really sorry about the trouble.

**Comment by ccheever** [comment]
Here's the commit that fixes the docs.
https://github.com/ccheever/chalk256/commit/47b522504addb0cfd93c22f86d519f5c75ac96ff
